const LIMIT_VALUES = {
  MIN_INPUT_LENGTH: 0,
  MAX_INPUT_LENGTH: 3000,
  MAX_SAFE_INTEGER: Number.MAX_SAFE_INTEGER,
  MAX_NAME_LENGTH: 5,
  MIN_PARTICIPANT: 2,
  MAX_PARTICIPANT: 50,
  MIN_ROUND: 1,
  MAX_ROUND: 100,
};

export default LIMIT_VALUES;
