const LIMIT_VALUES = {
  MIN_INPUT_LENGTH: 0,
  MAX_INPUT_LENGTH: 3000,
  MAX_SAFE_INTEGER: Number.MAX_SAFE_INTEGER,
  MAX_NAME_LENGTH: 5,
  MIN_PARTICIPANTS: 2,
  MAX_PARTICIPANTS: 50,
  MIN_ROUNDS: 1,
  MAX_ROUNDS: 100,
};

export default LIMIT_VALUES;
